@extends('adminlte::page')

@section('title', 'Edit – ' . $page->title)

@section('content_header')
    <div class="d-flex justify-content-between align-items-center">
        <h1 class="m-0">{{ $page->title }}</h1>
        <div class="d-flex" style="gap:.5rem;">
            <a href="{{ url($page->slug) }}" target="_blank" class="btn btn-info btn-sm">
                <i class="fas fa-eye mr-1"></i> View
            </a>
            <a href="{{ route('admin.pages.index') }}" class="btn btn-secondary btn-sm">
                <i class="fas fa-arrow-left mr-1"></i> Back
            </a>
        </div>
    </div>
@stop

@section('content')

@if(session('success'))
    <div class="alert alert-success alert-dismissible fade show">
        {{ session('success') }}
        <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
    </div>
@endif

@if($errors->any())
    <div class="alert alert-danger">
        <ul class="mb-0">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul>
    </div>
@endif

<div class="card card-outline card-primary">
    <div class="card-body">
        <form method="POST" action="{{ route('admin.pages.update', $page) }}" id="page-form">
            @csrf @method('PUT')
            @php $noContent = in_array($page->slug, ['home', 'shows', 'calendar', 'faq']); @endphp

            @if($noContent)
                <div class="alert alert-info">
                    <i class="fas fa-info-circle mr-1"></i>
                    This page's content is generated by the application template and cannot be edited here. You can still manage its SEO settings below.
                </div>
            @else
            <div class="form-group">
                @if($page->slug === 'contact')
                    {{-- CKEditor for contact page --}}
                    <textarea name="content" id="page-content">{{ old('content', $page->content) }}</textarea>
                @else
                    {{-- CodeMirror (raw HTML) for all other pages --}}
                    <textarea name="content" id="page-content" style="display:none;">{{ old('content', $page->content) }}</textarea>
                    <div id="codemirror-editor" style="border:1px solid #ced4da;border-radius:4px;font-size:13px;"></div>
                @endif
            </div>
            @endif

            {{-- SEO fields --}}
            <hr>
            <h5 class="mb-3"><i class="fas fa-search mr-1"></i> SEO</h5>
            <div class="row">
                <div class="col-md-6 form-group">
                    <label class="font-weight-bold">SEO Title</label>
                    <input type="text" name="seo_title" maxlength="255"
                           value="{{ old('seo_title', $page->seo_title) }}"
                           class="form-control" placeholder="Leave blank to use default format">
                    <small class="text-muted">Max 255 chars.</small>
                </div>
                <div class="col-md-6 form-group">
                    <label class="font-weight-bold">Meta Description</label>
                    <textarea name="seo_description" rows="2" maxlength="320"
                              class="form-control" placeholder="Leave blank to use default">{{ old('seo_description', $page->seo_description) }}</textarea>
                    <small class="text-muted">Max 320 chars.</small>
                </div>
                <div class="col-12">
                    <div class="custom-control custom-switch mb-3">
                        <input type="hidden" name="noindex" value="0">
                        <input type="checkbox" class="custom-control-input" id="noindex"
                               name="noindex" value="1"
                               @checked(old('noindex', $page->noindex))>
                        <label class="custom-control-label" for="noindex">
                            No-index this page <small class="text-muted">(hide from search engines)</small>
                        </label>
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-primary">
                <i class="fas fa-save mr-1"></i> Save
            </button>
            <button type="button" class="btn btn-secondary ml-2" onclick="openPreview()">
                <i class="fas fa-eye mr-1"></i> Preview
            </button>
        </form>

        {{-- Hidden form that POSTs current content to preview route in new tab --}}
        <form id="preview-form" method="POST" action="{{ route('admin.pages.preview', $page) }}" target="_blank" style="display:none;">
            @csrf
            <textarea name="content" id="preview-content"></textarea>
        </form>
    </div>
</div>

@stop

@section('css')
@if(!in_array($page->slug, ['home','shows','calendar','faq']) && $page->slug !== 'contact')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.17/codemirror.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.17/theme/dracula.min.css">
<style>
.CodeMirror { height: 600px; font-size: 13px; line-height: 1.6; }
</style>
@endif
@stop

@section('js')
@php $noContent = in_array($page->slug, ['home', 'shows', 'calendar', 'faq']); @endphp
@if(!$noContent && $page->slug === 'contact')
{{-- CKEditor 5 --}}
<script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script>
<script>
var ckEditor;

ClassicEditor.create(document.getElementById('page-content'), {
    toolbar: [
        'heading', '|',
        'bold', 'italic', 'underline', 'strikethrough', '|',
        'link', 'bulletedList', 'numberedList', 'blockQuote', '|',
        'insertTable', 'horizontalLine', '|',
        'undo', 'redo'
    ],
}).then(function (editor) {
    ckEditor = editor;
}).catch(function (err) {
    console.error(err);
});

document.getElementById('page-form').addEventListener('submit', function () {
    if (ckEditor) {
        document.getElementById('page-content').value = ckEditor.getData();
    }
});

function openPreview() {
    document.getElementById('preview-content').value = ckEditor ? ckEditor.getData() : '';
    document.getElementById('preview-form').submit();
}
</script>

@elseif(!$noContent)
{{-- CodeMirror for HTML pages --}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.17/codemirror.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.17/mode/xml/xml.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.17/mode/htmlmixed/htmlmixed.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.17/addon/edit/matchbrackets.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.17/addon/edit/closetag.min.js"></script>
<script>
var editor = CodeMirror(document.getElementById('codemirror-editor'), {
    value:         document.getElementById('page-content').value,
    mode:          'htmlmixed',
    theme:         'dracula',
    lineNumbers:   true,
    lineWrapping:  true,
    matchBrackets: true,
    autoCloseTags: true,
    indentUnit:    2,
    tabSize:       2,
});

document.getElementById('page-form').addEventListener('submit', function () {
    document.getElementById('page-content').value = editor.getValue();
});

function openPreview() {
    document.getElementById('preview-content').value = editor.getValue();
    document.getElementById('preview-form').submit();
}
</script>
@endif
@stop
